language: elixir
elixir:
  - 1.3.2
  - 1.5
  - 1.6
otp_release:
  - 17.5
  - 18.3
  - 19.0
  - 20.0
  - 20.2
  
sudo: false # to use faster container based build environment
notifications:
  email: false
